#!/bin/bash

wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -O $HOME/.git-prompt.sh
wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -O $HOME/.git-completion.sh

cat ./bash_profile > $HOME/.bash_profile
cat ./bashrc > $HOME/.bashrc
cat ./aliases >> $HOME/.aliases
cat ./functions >> $HOME/.functions

source $HOME/.bash_profile
