#!/bin/bash

sudo apt-get install -y build-essential cmake python-dev

wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -O $HOME/.git-prompt.sh
wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -O $HOME/.git-completion.sh

cat ./totoro > $HOME/.totoro
cat ./aliases >> $HOME/.aliases
cat ./functions >> $HOME/.functions

cat <<'EOT' >> $HOME/.bashrc

#
# Custom bashrc [.totoro]
#
[ -s "$HOME/.totoro" ] && . "$HOME/.totoro"

EOT

source $HOME/.profile

vim +PluginInstall +qall
cd $HOME/.vim/bundle/YouCompleteMe
./install.py --clang-completer --gocode-completer
