#!/bin/bash

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

cat ./gitconfig > $HOME/.gitconfig
cat ./screenrc > $HOME/.screenrc
cat ./vimrc > $HOME/.vimrc

mkdir -p $HOME/.vim
